version: "3.7"
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - default
    volumes:
      - redis:/data

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - 9000:9000
    networks:
      - default
    volumes:
      - minio:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data

  rabbitmq:
    image: rabbitmq:3.8.3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - default
    volumes:
      - rabbitmq:/var/lib/rabbitmq

networks:
  default:
    name: database
    attachable: true