version: "3.7"
services:
  mysqldb:
    image: mysql:5.7 # mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      default: {}

  # postgresdb:
  #   image: postgres:14 # postgres:11
  #   restart: always
  #   environment:
  #     POSTGRES_USER: my_user
  #     POSTGRES_PASSWORD: strong_password
  #     POSTGRES_DB: my_database
  #   volumes:
  #     - ./postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   networks:
  #     default: {}

  # mongodb:
  #   image: mongo:4.4 # mongo:3.6
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./mongo_data:/data/db
  #   networks:
  #     default: {}

networks:
  default:
    name: database
    attachable: true